default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: cosmosloth
  encoding: utf8
  collation: utf8

development:
  <<: *default
  database: zyvie_development

test:
  <<: *default
  database: zyvie_test

production:
  <<: *default
  database: zyvie_production
